services:
  - type: web
    name: aza-a2a
    env: python
    region: frankfurt
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
